version: '2'
services:
  # nginx-proxy
  proxy:
    build: ./docker/enginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # コンテナイベントの取得のためにdocker.sockをro[Read Only]でマウント
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./volumes/server/:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
    restart: always
    privileged: true
    environment:
      DEFAULT_HOST: www.*

  # https対応のためにSSL証明書を発行・管理を行う
  letsencrypt-proxy:
    image: jrcs/letsencrypt-nginx-proxy-companion
    privileged: true
    volumes:
      - ./volumes/server/:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - proxy
  web_db:
    image: mysql:5.7
    volumes:
      - "./volumes/wordPress/:/var/lib/mysql"
      - ./wordpress.sdql:/docker-entrypoint-initdb.d/install_wordpress.sql

    restart: always
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    image: wordpress:latest
    links:
      - "web_db:web_db"
    restart: always
    expose:
      - "80"
    depends_on:
      - web_db
    environment:
      WORDPRESS_DB_HOST: web_db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      VIRTUAL_HOST: www.*
