version: '2'
services:
  wordpress:
    image: wordpress:latest
    links:
      - "web_db:web_db"
    restart: always
    expose:
      - "80"
    depends_on:
      - web_db
    environment:
      WORDPRESS_DB_HOST: web_db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      VIRTUAL_HOST: www.*
networks:
  default:
    external:
      name: bridge
