version: '2'
services:
  wordpress:
    image: wordpress:latest
    links:
      - "web_db:web_db"
    restart: always
    expose:
      - "80"
    depends_on:
      - web_db
    environment:
      WORDPRESS_DB_HOST: web_db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      VIRTUAL_HOST: www.*
  web_db:
    image: mysql:5.7
    volumes:
      - "./volumes/wordPress/:/var/lib/mysql"
      - ./wordpress.sdql:/docker-entrypoint-initdb.d/install_wordpress.sql

    restart: always
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
networks:
  default:
    external:
      name: illyasviel
